### ISSUE TITLE
Change shortcuts for Mac

### ISSUE THREAD

**Issue by kaskavalci** [gsomoza/firefox-easy-container-shortcuts#1]
Thanks for the extension, I find it very useful.

However, ⌘+⇧+3 and ⌘+⇧+4 are reserved for screenshot capturing in Mac, making the 3d and 4th containers unusable. It would be nice if a different set is used for Mac.

**Comment by gsomoza** [comment]
Good suggestion. I'm using Mac but I didn't notice because I'm also using Teampaper Snap for capturing screenshots :)

Which other combo do you think would be a good alternative?

**Comment by kaskavalci** [comment]
⌘+⌥+[num] would be nice choice IMHO. I don't think there is a system-wide shortcut for that. Also I noticed ⌘+⇧+6 also captures screenshot so moving away from ⌘+⇧+number mapping would be good decision :)

**Comment by gsomoza** [comment]
Unfortunately ⌘+⌥+[num] is currently not possible in Firefox (not sure why). I can only either combine a main modifier key with ⇧, or not combine it at all. More info here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values

Maybe, only in Mac, we could use the actual Ctrl key instead of ⌘ – would that interfere with any other shortcuts? I.e. Ctrl + ⇧ + [num]

**Comment by gsomoza** [comment]
Just saw your PR and merged it 👍 thanks! Will also publish a new release in a moment.

**Comment by TuxyKey** [comment]
for me the alt+Shift+3 is the euro sign (as an example) ...
The better sollution would be control+number that one is not reserved for anything at least not that i know of.. i'm currently on Mojave and typing on a custom keyboard but default layout. it's just a tada68 nothing fancy.. the layout is standard Mac osx so this problem has noting to do with my setup.. 
i love this addon but had to disable it.. because every time i tweet someone and use the € sign a container tab opens..

**Comment by kaskavalci** [comment]
I have this problem too. I thought about mapping CTRL key as you suggested but Mac's keyboard scheme is not comfortable for that. I open more tabs than I type € sign so that was the trade-off for me.

**Comment by gsomoza** [comment]
I also have to live with that trade-off for now. If anyone notices a change in the Firefox API so we can use a better mapping such as ⌘+⌥+[num] please comment here and we can add it.
