### ISSUE TITLE
Reopen in container shortcut

### ISSUE THREAD

**Issue by tejaslodaya** [gsomoza/firefox-easy-container-shortcuts#11]
Suppose I am on a webpage, and I want to reopen the same link in a different container, in the same tab (not a new tab). 

Is it possible?

CC: @gsomoza

**Comment by gsomoza** [comment]
Just to clarify, you would like to convert the webpage in the current tab to a different session? That's possible and there's already another plugin for it (which is why I didn't do it): [Switch Container](https://addons.mozilla.org/en-US/firefox/addon/switch-container/?src=search)

Closing for now cause I assume that answers your question, but feel free to follow up with other questions or suggestions!

**Comment by kyounger** [comment]
Up to you to decide to reopen (hah) this issue, but I checked the Switch Container plugin, and while it does exactly that, it doesn't provide any keyboard shortcuts.

Additionally, the default containers plugin allows also already has the option to reopen a tab in another container (by right clicking on the tab, "Reopen in Container"). 

I looked at the source code, perhaps there is an api that you can access for this? Sorry I've never written an extension so no clue how to even look for where that might be.

**Comment by kyounger** [comment]
I'll leave this here, in case it's helpful for anyone else. I just ended up writing my own personal plugin, but it's open source, too: https://github.com/kyounger/kennys-shortcuts-ff-ext

It's easy enough to clone, change the names of the containers, zip up, and have Mozilla sign it for you to install yourself.

There's probably a way to make this generic: creating a UI on a preferences page that allows you to map a series of shortcuts to specific container names. This was literally my first plugin I've ever written, and don't have time to explore creating the rest of that.

**Comment by gsomoza** [comment]
Congratulations on your first Firefox plugin! I think it's a good idea to do it, and thanks for making it open-source.

I also like the idea of having this functionality as an optional complement to our Easy Container Shortcuts plugin, so I don't think I'll incorporate the feature directly into this plugin – just to keep this one simple and clear. But anyone looking for the functionality can now find it in this ticket with two options (Switch Container + your repo), so that's good for now IMO.
