### ISSUE TITLE
Toolbar shortcut

### ISSUE THREAD

**Issue by Novantric** [gsomoza/firefox-easy-container-shortcuts#18]
Hi,
Nice simple addon. Yet one feature I would love is a button you can have on the toolbar that adds a new tab when you press it in the current container, so a shortcut to `Ctrl + Alt + T`.
Or another similar shortcut that you can set to be a specific container, e.g. `Ctrl + Shift + 1`. I would find this super useful.
Alternative existing solutions welcomed.

**Comment by gsomoza** [comment]
Thanks for the suggestions, it's great to hear input like this.

The second suggestion I think can be fixed easily with existing Firefox features: you could remap the shortcut for a specific container into any key other combination that make more sense to you, more info about that here: https://github.com/gsomoza/firefox-easy-container-shortcuts/issues/15#issuecomment-598763922 – hopefully that works for you!

I don't think we'll add the toolbar button because this plugin is only about keyboard shortcuts. But building plugins for Firefox is actually quite easy, so if you know a bit of JavaScript I encourage you to give it a try!

Will close this ticket for now, but all suggestions are welcome so feel free to keep brainstorming! It's the only way this plugin can get better.
